# Generated by Django 5.2.3 on 2025-06-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tudo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tudo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tudo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
